### PR TITLE
Add guide for historical research

### PR DESCRIPTION
**Pull request by erazlogo**
## Edited
I edited `04 - Guides, Workflows, & Courses/for Academic Writing.md` -- added a link to my workflow for historians.

## Added
I did not add any pages.

## Checklist
- [ ] before creating a new note, I searched the vault
- [ ] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Review by lguenth — CHANGES_REQUESTED** [review]
Thank you for contributing your guide, it's much appreciated. :) Could you please remove the asterisk `*` at the end of the line? Otherwise it's recognised as italics.

If you want, you could also add a page for yourself in `01 Community/People/`with the Author template (`00 - Contribute to the Obsidian Hub/01 Templates/T - Author.md`). If you don't want that, please remove the wikilink to your name. You can instead link to any external reference of yourself, such as a social media account, your Publish site etc.

If you need help with anything, feel free to ask – that's what I'm here for. :wink:

**Comment by lguenth** [comment]
To make further edits to the text
1. go to `Files changed` (it's at the top of this page),
2. click on the three dots on the top right corner of the note
3. press `Edit file`, this opens the same editor view that you used yesterday

Screenshot:
grafik

**Comment by erazlogo** [comment]
Ok, I made the changes. The author pages on the Hub seem to list people with plugins and themes mostly and I haven't made any yet, so I just removed the wikilink from the page. Thanks!

**Review by lguenth — APPROVED** [review]
Perfect, thank you very much! I'll merge the changes which makes them part of the hub. You can then immediately see them on Github but it will take roughly a week for them to appear on the Publish site.

**Pull request merged**
