### PR TITLE
Obsidian releases scripts

### LINKED ISSUE #8: community themes misses author, screenshot and modes
# Actual Behavior
image

# Suggested Behavior

image

_(format and order could be changed)_

`community-css-themes.json` provides additional info but it's not utilized.

### PR DESCRIPTION
**Pull request by argenos**
- Added scripts used to pre-populate the plugin and theme notes from the obsidian-releases repo
- Changes to 02 and 04 fix #8 
- Updated the plugin category template to include related categories 
- Updates to category files from the last csv files

## Checklist

- [x] I have renamed all attached images with descriptive file names (or I did not include any images)
- [x] Before creating a new note, I searched the vault (or I only edited existing notes)

### CODE REVIEW

**Review by konhi — CHANGES_REQUESTED** [review]
Some images don't work due to wrong branch (some use main, some use master)

image

**Comment by konhi** [comment]
OMG, so awesome PR!
Great job! Remember that some plugins use master branch and others use main. Keep in mind that also some of them specify in `.json` that they use one, but actually use other. I had script written that finds repositories like that. I could make PR to obsidian-releases to fix that.

**Review by kometenstaub — APPROVED** [review]
Looks good to me.

**Comment by argenos** [comment]
@konhi I think https://github.com/obsidian-community/obsidian-hub/commit/2857102061a345f5c940c673759b85898b153f7e should've fixed that in theory, but yeah... It might be that some don't match in practice what is in the JSON file. If you have a working solution, feel free to push it in this branch!

**Comment by konhi** [comment]
@argenos thanks for fixing that! since script works fine, it should be fixed in obsidian-releases which I will try to do in next few days!

**Review by konhi — APPROVED** [review]

**Comment by konhi** [comment]
@argenos sorry, I didn't know that I have to manually approve changes! Today I learnt 😅

**Pull request merged**
