### PR TITLE
Update MOCs

### PR DESCRIPTION
**Pull request by argenos**
- This PR is an automated change that updates MOCs with the `update-mocs.py` script.

## Checklist

- [ ] I have renamed all attached images with descriptive file names (or I did not include any images)
- [ ] Before creating a new note, I searched the vault (or I only edited existing notes)
- [ ] (Optional) In case I created a new note in the folder `04 - Guides, Workflows, & Courses`, I added a link to the new note(s) in one of the `for {group X}` overviews ([listed here](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses)).

### CODE REVIEW

**Comment by claremacrae** [comment]
I hadn't seen this when I offered to update MOCs after adding some .md extensions...
Apologies - I think this is obsolete now?

**Comment by argenos** [comment]
In that case, should I close this one?

**Comment by claremacrae** [comment]
> In that case, should I close this one?

Yes, I think so.

**Comment by claremacrae** [comment]
Done

**Pull request closed without merging**
