### PR TITLE
Prevent theme, plugin and author files being created that differ only in case of name

### PR DESCRIPTION
**Pull request by claremacrae**
## Changes

- Introduce class `FileNameCaseCollisionsPreventer` in `utils.py` that:
    - builds a list of files in the given directory,
    - and can be used to normalise the names of any output files in that directory
- Updated `.github/scripts/tests/test_utils.py` to use the above, when writing notes for:
    - themes
    - plugins
    - authors
- Also in `utils.py`:
    - Rename `get_output_dir()` to `get_output_path()`
    - Added new `get_output_dir()` that really does return a directory
    - Added tests for the above

This work was done by pairing with @andynu - who was involved in all commits except the last one, where I moved `FileNameCaseCollisionsPreventer ` to `utils.py`.

## Context:

- #308 
- #598
- #607 

## Checklist

Not applicable...

### CODE REVIEW

**Comment by claremacrae** [comment]
I realised a small limitation in what we created...

If a new author releases 2 new themes or plugins in the same week, and capitalises their user name inconsistently, both files will get created, as we don't update the dictionary as each new file comes in...

I say 'small' as the chances of a new author both these is very small:

- having their first 2 new things accepted in the same week
- _and_ getting their name inconsistent between them (which is itself very rare)

So, given that we have fixed the most common case, I would really like to get this merged before this week's GitHub Action cron jobs run, if at all possible...

**Comment by claremacrae** [comment]
Hi @kometenstaub, as you have kindly done reviews before, if by any chance you had time to give this a once-over, it would really help.

It was done entirely by pairing - I just can't approve it because we started on my machine, so it's done in my account.

**Review by kometenstaub — APPROVED** [review]
I followed all the logic, and it looks good to me! Thank you for implementing this. :)

**Comment by claremacrae** [comment]
Thank you very much!

**Pull request merged**
