### PR TITLE
Added reminder to link newly created notes

### PR DESCRIPTION
**Pull request by chrisgrieser**

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Now it is really a `< 5 line change`, @claremacrae :)

**Comment by claremacrae** [comment]
Who would've thought a one-line PR might generate discussion 😜 

I really like the idea of adding this as a check-list point in the PR template, with this text:

`- [ ] I linked any newly created notes in a MoC or overview note.`

My hesitation is over whether all contributors will understand what type of MoC file should be updated.

The reason is that the MoC files with names beginning 🗂️ are machine-generated by a Python script... And there is no value in anyone hand-editing them to add new files... Is there a likelihood that people will think that this is what they need to do, to check that box?

I don't know - it may just be my lack of PKM/Obsidian-specific vocabulary at this point..

So, what *do* you mean by *MoC" here, @chrisgrieser ?

**Comment by chrisgrieser** [comment]
> So, what do you mean by *MoC" here, @chrisgrieser ?

The overview notes, like e.g. `for Theme designers` where for example @jdanielmourao forgot to link his guide.

I am thinking – is there any other case than the guides where we do *not* have autolinking by your scripts? 🤔

**Comment by claremacrae** [comment]
> I am thinking – is there any other case than the guides where we do _not_ have autolinking by your scripts? 🤔

I'm really struggling to express this in typed words...

**Comment by claremacrae** [comment]
> > I am thinking – is there any other case than the guides where we do _not_ have autolinking by your scripts? 🤔
> 
> I'm really struggling to express this in typed words...

Maintainers need to understand how users might want to arrive at some new content.

There are various pages in the hub that are curated collections of links to a subset of the pages...

- Sometimes those curated collections are inside a 🗂️ file
- Sometimes they are in a Categories file
- Sometimes they are in a "for person of type x" file. like "for Creative writing"
- there are probably others that I forget

So an experienced hub user will know where to add a link to... which one or more places...

For others, it's probably fine that they add a file, and a more experienced Hub maintainer may add links later.

I am trying to sympathise with users who don't understand the higher-level structure... (I'm not sure I do)

**Comment by claremacrae** [comment]
I think I'm probably worrying about nothing, and the new text is definitely an improvement... I've asked in Discord to see what others think...
https://discord.com/channels/686053708261228577/915679988118863933/917049725386104832

**Review by claremacrae — APPROVED** [review]
Approved - thanks!

**Comment by claremacrae** [comment]
Talking to myself again ... :-) 

I've been looking at the existing auto-generated MOCs - and lots of them are embedded in pages with meaningful content...

This change is definitely an improvement - I'm sure it will help... Merging...

**Comment by claremacrae** [comment]
Thank you! 😀

**Pull request merged**
