### PR TITLE
Improve documentation within scripts.

### PR DESCRIPTION
**Pull request by andynu**
- Add/improve docstrings
- Add comments.

### CODE REVIEW

**Review by claremacrae — APPROVED** [review]
This all made sense. Thank you!

**Comment by claremacrae** [comment]
Hi @andynu, Thank you!

I see there are merge conflicts. Sorry I don't have time to deal with them tonight.

**Comment by andynu** [comment]
Oh, no worries. I'll take a look. Thanks.

**Comment by claremacrae** [comment]
Thanks!

**Pull request merged**
