### PR TITLE
Additions to 'How to update your plugins and CSS for live preview'

### PR DESCRIPTION
**Pull request by claremacrae**
- Add some example code to 'How to update your plugins and CSS for live preview'
- Add some links to that page so it's easier to find

### CODE REVIEW

**Comment by claremacrae** [comment]
@argenos Note for reviewing: the code snippet `isLivePreviewSupported()` is invented as I don't have a development environment... 

Would it need to receive `this` as a parameter, i.e. `isLivePreviewSupported(this)`

...  or even `isLivePreviewSupported(this.app)`

**Comment by chrisgrieser** [comment]
I have no idea about the `isLivePreviewSupported()`, but otherwise everything looks fine to me, so I'll approve this to unblock the merging :)

**Comment by claremacrae** [comment]
Thanks @chrisgrieser !

**Review by chrisgrieser — APPROVED** [review]
LGTM!

**Pull request merged**
