### PR TITLE
Add sponsor link to Breadcrumbs

### PR DESCRIPTION
**Pull request by SkepticMystic**
- Added/Edited note ...

## Checklist

- [x] I have renamed all attached images with descriptive file names (or I did not include any images)
- [x] Before creating a new note, I searched the vault (or I only edited existing notes)

### CODE REVIEW

**Review by argenos — COMMENTED** [review]
Since you have more than one plugin now, do you want to add that in the [[SkepticMystic]] note and embed it instead?

**Comment by SkepticMystic** [comment]
That'd be awesome, please do :)

**Comment by kometenstaub** [comment]
> That'd be awesome, please do :)

I think she wants you to do that (with a new commit to this PR).

**Comment by SkepticMystic** [comment]
Sure thing, I will do that!

**Comment by SkepticMystic** [comment]
I have added a [[SkepticMystic]] note, so I'll close this PR :)

**Pull request closed without merging**
