### PR TITLE
Rename author derwish-pro to dy-sh

### LINKED ISSUE #261: Rename author derwish-pro to dy-sh
In https://github.com/obsidianmd/obsidian-releases/pull/722 the community releases were updated for the rename of plugin author `derwish-pro` to `dy-sh`.

In commit 857e7cf2d1e7a39bc1cb9dec2cb0ea15b1637216 here in the Obsidian Hub, the new `01 - Community/People/dy-sh.md` note was created automatically...

This issue is to update the notes for all that author's plugins, to point to the new author name.

### PR DESCRIPTION
**Pull request by claremacrae**
This fixes #261 - see the detail there for more information.

## Edited

- Updated the author's 5 plugin pages to use new account name
- Removed the note for the old account name
- Manually updated the URL in the note for the new account name

(For this last point, a better solution would be to put in a PR to whichever of the manifest.json files might have the old account name...)

### CODE REVIEW

**Comment by argenos** [comment]
Is there a PR in Obsidian releases related to this?

**Comment by claremacrae** [comment]
> Is there a PR in Obsidian releases related to this?

Yes, it's in the linked issue - see the description at top of this one...

**Comment by claremacrae** [comment]
> In [obsidianmd/obsidian-releases#722](https://github.com/obsidianmd/obsidian-releases/pull/722) the community releases were updated for the rename of plugin author `derwish-pro` to `dy-sh`.
> 
> In commit [857e7cf](https://github.com/obsidian-community/obsidian-hub/commit/857e7cf2d1e7a39bc1cb9dec2cb0ea15b1637216) here in the Obsidian Hub, the new `01 - Community/People/dy-sh.md` note was created automatically...
> 
> This issue is to update the notes for all that author's plugins, to point to the new author name.

**Comment by claremacrae** [comment]
> Is there a PR in Obsidian releases related to this?

Hi @argenos 

_This time with a ping, and all the info in one reply..._

Yes. This one: https://github.com/obsidianmd/obsidian-releases/pull/722

**Comment by dy-sh** [comment]
Hello. I have edited manifest.json in my plugin repositories. Do I now need to make a new release on github with a version upgrade so that everything is updated?

**Comment by dy-sh** [comment]
I did not know about the hub, this is a great initiative! By the way, you may be interested in placing a link to my obsidian training course in Russian. Perhaps your link is indexed by Google and this will help Russian-speaking users find this course. At the moment, YouTube has very little information on obsidian in Russian. In this course, I covered how to write notes/documentation in Markdown, why you should do it in Markdown, and how to use Obsidian for this (how to set it up, which plugins to install, how to organize your library of files, and even how to write your own plugin).
I think this is one of the most complete obsidian courses out there and it has very good reviews. I also dream of someone helping me with its translation into English.
https://www.youtube.com/watch?v=aeebp25l9Gg&list=PLrRc3UisLr6KVOYhzpSnywtHkCi2PEza5

**Comment by claremacrae** [comment]
> Hello. I have edited manifest.json in my plugin repositories. Do I now need to make a new release on github with a version upgrade so that everything is updated?

Hi @dy-sh  That's great, thanks. As far as I know, there's no need to do a re-release of your plugins. Browsing your Community plugins in Obsidian, the "By" link already goes to your new account:

image

**Comment by claremacrae** [comment]
> I did not know about the hub, this is a great initiative! By the way, you may be interested in placing a link to my obsidian training course in Russian. Perhaps your link is indexed by Google and this will help Russian-speaking users find this course. At the moment, YouTube has very little information on obsidian in Russian. In this course, I covered how to write notes/documentation in Markdown, why you should do it in Markdown, and how to use Obsidian for this (how to set it up, which plugins to install, how to organize your library of files, and even how to write your own plugin).
> I think this is one of the most complete obsidian courses out there and it has very good reviews. I also dream of someone helping me with its translation into English.
> https://www.youtube.com/watch?v=aeebp25l9Gg&list=PLrRc3UisLr6KVOYhzpSnywtHkCi2PEza5

Fantastic. I've added it as #264 so we don't forget it.

If you had the time and wanted to add it, a Pull Request would be very welcome...  

We do have a note on [Contributing](https://publish.obsidian.md/hub/CONTRIBUTING) - the main thing is probably to point you to the Templates in 
[`00 - Contribute to the Obsidian Hub/01 Templates/`](https://github.com/obsidian-community/obsidian-hub/tree/main/00%20-%20Contribute%20to%20the%20Obsidian%20Hub/01%20Templates)

If in doubt, use `T - New Note.md`.

**Review by argenos — APPROVED** [review]

**Pull request merged**
