### PR TITLE
Add an "Open in Obsidian" button to plugins

### PR DESCRIPTION
**Pull request by argenos**
- With @chrisgrieser's idea and @SlRvb CSS magic, this PR adds an "Open in Obsidian" button to all plugins
- New notes for plugins released this week 

## Checklist

- [x] I have renamed all attached images with descriptive file names (or I did not include any images)
- [x] Before creating a new note, I searched the vault (or I only edited existing notes)

### CODE REVIEW

**Comment by konhi** [comment]
@argenos So cool feature!

Are you sure that button works? When I try to paste the link into browser, I'm getting that error.
image

Although when I do that while Obsidian vault is opened, it just changes focus into Obsidian app, but the plugin doesn't open.

**Comment by argenos** [comment]
@konhi it should! You might need to enable the css snippet included in ac16550  (`.obsidian/snippets/hh-buttons.css`)

**Comment by chrisgrieser** [comment]
@konhi Do you have the Hotkey Helper Plugin installed?

**Review by kometenstaub — APPROVED** [review]
It works with the CSS snippet enabled and Hotkey Helper installed.

**Comment by konhi** [comment]
Oh, I see. Shouldn't it be enabled in vault by default, then?

**Comment by chrisgrieser** [comment]
no, it needs to be enabled in *your* vault :P

**Review by konhi — APPROVED** [review]
Great feature!

**Pull request merged**
