### PR TITLE
Update "How to add your plugin to the community plugin list"

### PR DESCRIPTION
**Pull request by lomky**
## Edited

Removed the defunct key `branch` from the instructions for adding your plugin to the directory. See [this PR](https://github.com/obsidianmd/obsidian-releases/pull/2280) naming the field as invalid. Remaining instructions revalidated!

## Checklist
- [ ] ~~before creating a new note, I searched the vault~~
- [ ] ~~new notes have the `.md` extension~~
- [ ] ~~(if applicable) attached images have descriptive file names~~
- [ ] ~~(if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses~~

### CODE REVIEW

**Review by ericaxu — APPROVED** [review]

**Comment by lomky** [comment]
Thank you for the review! Could I please get the workflow run approval so I can merge?

**Comment by argenos** [comment]
Hi @lomky, could you resolve the merge conflicts?

**Comment by lomky** [comment]
Looks like I need approval on the workflows, again!

**Comment by claremacrae** [comment]
I've started the workflow.

**Review by argenos — APPROVED** [review]

**Pull request merged**
