### PR TITLE
Add dy-sh's Obsidian Training Course in Russian (Fixes #264)

### LINKED ISSUE #264: Add a note for dy-sh's Russian Obsidian course
It would be good for a Course note to be added, to capture this information from @dy-sh...

I would think that adding a new file in [04 - Guides, Workflows, & Courses/Courses/](https://github.com/obsidian-community/obsidian-hub/tree/main/04%20-%20Guides%2C%20Workflows%2C%20%26%20Courses/Courses) would work well.

> I did not know about the hub, this is a great initiative! By the way, you may be interested in placing a link to my obsidian training course in Russian. Perhaps your link is indexed by Google and this will help Russian-speaking users find this course. At the moment, YouTube has very little information on obsidian in Russian. In this course, I covered how to write notes/documentation in Markdown, why you should do it in Markdown, and how to use Obsidian for this (how to set it up, which plugins to install, how to organize your library of files, and even how to write your own plugin).
I think this is one of the most complete obsidian courses out there and it has very good reviews. I also dream of someone helping me with its translation into English.
https://www.youtube.com/watch?v=aeebp25l9Gg&list=PLrRc3UisLr6KVOYhzpSnywtHkCi2PEza5

_Originally posted by @dy-sh in https://github.com/obsidian-community/obsidian-hub/issues/262#issuecomment-1021766148_

### PR DESCRIPTION
**Pull request by lguenth**
Fix for #264 as mentioned in #262 

## Edited
- Made some additions to dy-sh's author page, such as their YouTube link and the course playlist
- Added course to Guides for Beginners with a note that it's specifically for Russian speakers

## Added

A new note for the Obsidian Training Course in Russian, incl. a link to the playlist + the embed of the first part, with the description adapted from what dy-sh added in the renaming PR. I also cross-referenced some of the other guides.

## Checklist
- [x] before creating a new note, I searched the vault
- [x] new notes have the `.md` extension
- [x] (if applicable) attached images have descriptive file names
- [x] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Comment by lguenth** [comment]
Uh, I'm not quite sure why the dataview introduction is listed here as a related commit... Did I do something wrong? It looked fine locally. :frowning:

**Comment by kometenstaub** [comment]
> Uh, I'm not quite sure why the dataview introduction is listed here as a related commit... Did I do something wrong? It looked fine locally. 😦

Did you make another branch from main or from the dataview branch?
You can interactively rebase this branch and remove the dataview commit, then force-push. Let me know if you'd like me to do that.

**Comment by kometenstaub** [comment]
Since you are a hub contributor now, you can also just use the obsidian-community repo as origin and don't need to maintain two remote repos (origin and upstream). Then you can pull in updates from main directly.

**Comment by claremacrae** [comment]
> > Uh, I'm not quite sure why the dataview introduction is listed here as a related commit... Did I do something wrong? It looked fine locally. 😦
> 
> Did you make another branch from main or from the dataview branch? You can interactively rebase this branch and remove the dataview commit, then force-push. Let me know if you'd like me to do that.

_This is about my 5th attempt at trying to draft something diplomatic here..._

I'm feeling a little nervous about this.. I think your recommending some quite complicated and potentially risky things here... Especially in view of the next message talking about pushing directly to the hub...

**Comment by claremacrae** [comment]
> Uh, I'm not quite sure why the dataview introduction is listed here as a related commit... Did I do something wrong? It looked fine locally. 😦

Looking at the network of commits in your repo, I'm struggling to understand the links between the 3 branches, for 3 different PRs

https://github.com/lguenth/obsidian-hub/network

image

**Comment by claremacrae** [comment]
Here is a zoomed out view...

image

**Comment by claremacrae** [comment]
I think we need to figure out how you are creating branches when starting pull requests.... I'm not sure that this will be fixed by pushing directly to the Hub repo...

What IDE are you using, and how are you creating your branches?

To be honest, I think this is probably best fixed by someone pairing with you for a little while, screen-sharing, to help understand which of the many possible git confusions might be (understandably) tripping you up....

**Comment by kometenstaub** [comment]
> I'm feeling a little nervous about this.. I think you're recommending some quite complicated and potentially risky things here... Especially in view of the next message talking about pushing directly to the hub...

Right now it is on a branch of his fork, so whether force-pushing after a PR has been opened or a new PR should be opened would need to be something we have to discuss. 
As long as no-one has reviewed something before from a PR or made changes based on that branch, I don't have a problem with it in this case, but I can see that it might create issues if it is done too freely.

I agree that force-pushing to this repo can be dangerous. The main branch is protected, but if it is force-pushed to an incorrect branch (a different one to this PR), the work on it could get lost, I didn't think about that when I wrote my answer. Thank you for making me rethink it :)

**Comment by kometenstaub** [comment]
I had the same confusion as @claremacrae when I saw the branches, and I agree that it would be a good to understand how you create them.

**Comment by lguenth** [comment]
@claremacrae @kometenstaub 
First of all, thank you so much for taking your time to look into my mess and trying to help me.
I think I now know what happened.

I normally create branches with `git checkout -b branch-name` because that's how my linguistics prof once taught me and I simply must have forgotten that I wasn't on the main branch before doing that or I wrongly assumed that this method automatically branches from main... Which is obviously not the case.

I agree 100% that I should do my changes on my fork because I don't want to mess anything up here in the community repo. Doing reviews on text additions by other contributors here on GitHub is still something I can do but I think I need to go look at a git primer again. I should have noticed my error before opening a PR. I want to apologize for that.

Should I close the PRs and start fresh on my fork? I think I might complicate things if I try to fix what I did with rebasing etc.

**Comment by claremacrae** [comment]
> @claremacrae @kometenstaub First of all, thank you so much for taking your time to look into my mess and trying to help me. I think I now know what happened.

You're welcome!
 
> I normally create branches with `git checkout -b branch-name` because that's how my linguistics prof once taught me and I simply must have forgotten that I wasn't on the main branch before doing that or I wrongly assumed that this method automatically branches from main... Which is obviously not the case.

Ah yes, I did wonder if that might be the cause... I've certainly done that myself before... It's nothing to worry about...

> Should I close the PRs and start fresh on my fork? I think I might complicate things if I try to fix what I did with rebasing etc.

Thank. If you don't mind doing that, I think it's probably safest, so yes please.

**Pull request closed without merging**
