### PR TITLE
Create Drafting (Android).md

### PR DESCRIPTION
**Pull request by sensen**
Adding Drafting to Auxiliary Tools, a plain text editor for Android that coexists with Obsidian.

## Checklist
- [x] before creating a new note, I searched the vault
- [x] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Review by claremacrae — CHANGES_REQUESTED** [review]
Many thanks for the contribution.

It looks like this page was created from scratch rather than from the appropriate template.

I'm on mobile at the moment, so limited in what I can test out.

But these links should be useful:

- [Contribute to the Obsidian Hub](https://publish.obsidian.md/hub/00+-+Contribute+to+the+Obsidian+Hub/🗂%EF%B8%8F+00+-+Contribute+to+the+Obsidian+Hub)
- [example page for an auxiliary tool](https://github.com/obsidian-community/obsidian-hub/blob/main/02%20-%20Community%20Expansions/02.05%20All%20Community%20Expansions/Auxiliary%20Tools/Drafts%20App.md)
- [template to use for auxiliary tool](https://github.com/obsidian-community/obsidian-hub/blob/main/00%20-%20Contribute%20to%20the%20Obsidian%20Hub/01%20Templates/T%20-%20Auxiliary%20tool.md)

**Comment by sensen** [comment]
Thank you for the links!

I thought the meta at the top is something that's managed automatically.

I've made the changes.

**Review by claremacrae — APPROVED** [review]
Super, thanks very much.

**Comment by claremacrae** [comment]
Thank you - this will get published when the automated jobs add its footer, and add it to the MoCs, next week...

**Comment by sensen** [comment]
Thank you so much! ♥️

**Pull request merged**
