### PR TITLE
add resource in academics section

### PR DESCRIPTION
**Pull request by MarcosNicolau**
## Edited

Academics sections

## Added

Added a resource.

## Checklist
- [x] before creating a new note, I searched the vault
- [x] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Review by claremacrae — CHANGES_REQUESTED** [review]
Thanks for the contribution.

For tidiness, please could you put the link under one of the existing headings?

Thanks.

**Comment by MarcosNicolau** [comment]
Hi,

Sure, I'll do it asap!

And thank you for the review!!

**Comment by MarcosNicolau** [comment]
Hello, 

Sorry that it took me so long to make the changes. I've been on vacation and I didn't have a pc with me!

Thanks!

**Review by claremacrae — APPROVED** [review]

**Comment by claremacrae** [comment]
Closing and reopening to try and get the checks to run.

**Comment by claremacrae** [comment]
Many thanks for this, @MarcosNicolau.

**Pull request merged**
