### PR TITLE
Create Johnny ✨.md

### PR DESCRIPTION
**Pull request by jsmorabito**
## Added
add person page for myself to the community folder 

## Checklist
- [x] before creating a new note, I searched the vault
- [x] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Comment by kometenstaub** [comment]
I think there’s a template for people files.

**Comment by jsmorabito** [comment]
> I think there’s a template for people files.

is this the correct one https://publish.obsidian.md/hub/00+-+Contribute+to+the+Obsidian+Hub/01+Templates/T+-+Author ?

I removed the top two links so my page looks like the one there

**Comment by kometenstaub** [comment]
https://github.com/obsidian-community/obsidian-hub/blob/main/00%20-%20Contribute%20to%20the%20Obsidian%20Hub/01%20Templates/T%20-%20Author.md

**Review by claremacrae — CHANGES_REQUESTED** [review]

**Comment by claremacrae** [comment]
Replaced by #588

**Pull request closed without merging**
