### PR TITLE
Updated the list of plugins using jest

### PR DESCRIPTION
**Pull request by franciskafieh**
## Edited
Updated the list of plugins using jest

## Added
Added a simple python script to format links for future contributors (so they are not limited to the provided regex, which seems more complicated). This is a comment.

## Checklist
- [ ] before creating a new note, I searched the vault
- [ ] new notes have the `.md` extension
- [ ] (if applicable) attached images have descriptive file names
- [ ] (if applicable) for new notes in the folder "04 - Guides, Workflows, & Courses", I added a link to them in one of the "for {group X}" overviews: https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/%F0%9F%97%82%EF%B8%8F+04+-+Guides%2C+Workflows%2C+%26+Courses

### CODE REVIEW

**Comment by franciskafieh** [comment]
Found an issue with my PR. the formatter lists https://github.com/greater-than/Obsidian-Tracker-Plus as https://github.com/greater/than-Obsidian-Tracker-Plus.

In other words, my script does not work if the author has a dash in their name. I will update and fix when I have time

**Comment by claremacrae** [comment]
Thanks for looking at this, and for spotting the issue.

**Review by argenos — APPROVED** [review]

**Comment by franciskafieh** [comment]
hey @claremacrae. Since you are the owner of the obsidian-repos-downloader, would you by any chance be able to host this simple formatter python script on it, too? This way the user does not need to make their own file and copy+paste the code manually to format (they will already have your repo cloned)

```py
from pathlib import Path

for path in Path('plugins').rglob('jest.config.*'):
    parts = path.parts
    author = parts[1]
    name = parts[2]
    print(f"- {author}/[{name}](https://github.com/{author}/{name})")
```
I propose getting rid of the previous command `find . -name jest.config.\* | grep -v node_modules | sort` since it is not X-platform (e.g. won't work on Windows tmk). The user will already have Python 3 downloaded (since it's needed to run the repo downloader), so this script shouldn't be an issue.

P.S. I will submit an updated list of jest plugins in a few minutes

**Review by franciskafieh — COMMENTED** [review]
updated list of plugins and changed script

**Comment by franciskafieh** [comment]
Any updates on this? Thank you.

**Review by claremacrae — APPROVED** [review]

**Comment by claremacrae** [comment]
Hi @franciskafieh - thanks very much indeed for doing this! 🎉

**Pull request merged**
