### PR TITLE
Add Web Clipper Bookmarklet

### PR DESCRIPTION
**Pull request by kepano**
Added Web Clipper Bookmarklet to auxiliary tools

### CODE REVIEW

**Review by chrisgrieser — COMMENTED** [review]
👍 Thanks for the addition!

**Review by chrisgrieser — APPROVED** [review]

**Comment by claremacrae** [comment]
@kepano Hi and thanks for the contribution!

How would you feel about making a small change to it, based on the following? If you'd rather not, them I'm happy to merge it and move the new line down a bit...

But by way of explanation for future reference...

I see that you've added a new Others section in between this pair of lines...

`%% Begin Hub: Released contributions %%`
`%% End Hub: Released contributions %%`

This makes sense - and it's maybe not totally obvious from those comments, but the text between them gets over-written by script...

So for ease of maintenance, the idea is instead to un-comment the "others" section a bit lower down...

**Comment by kepano** [comment]
Ok, I wasn't sure how that part works. Feel free to move the "Other" section below, or if you think there is a new category that this should fit into, I'm okay with that too!

**Comment by claremacrae** [comment]
Yes, we'll try and make it clearer...

It's all good, and I'll go ahead and merge it - thanks again!

**Pull request merged**
