### PR TITLE
Added Link to the Composite Vault Guide by @tzhouhc

### PR DESCRIPTION
**Pull request by chrisgrieser**

### CODE REVIEW

**Comment by tzhouhc** [comment]
I'm not actually at `https://github.com/tzhou`

**Comment by chrisgrieser** [comment]
Ah, thought that was you 🙈 
fixed

**Comment by kometenstaub** [comment]
Maybe squash the commits and change the commit message so that we don't reference a wrong user? @chrisgrieser

**Comment by chrisgrieser** [comment]
still haven't figured out how to change commit messages 🙈 

feel free to fix it?

**Comment by kometenstaub** [comment]
I can do that tomorrow.

**Review by kometenstaub — APPROVED** [review]

**Pull request merged**
