### PR TITLE
Update/Add D&D Snippets & Templates

### PR DESCRIPTION
**Pull request by SlRvb**
- Added my center table css snippet
- Added a couple D&D related templates
- I created a new TTRPG template folder since these didn't quite fit elsewhere in the template folder
- Added TTRPG related Dataview Query in dataview templates folder
- Updated my theme to link to the center table snippet and added the WOTC to my Alt Themes Snippet note

## Checklist

- [x] I have renamed all attached images with descriptive file names (or I did not include any images)
- [X] Before creating a new note, I searched the vault (or I only edited existing notes)

### CODE REVIEW

**Review by claremacrae — APPROVED** [review]
I've reviewed all these changes and they look really good to me. As far as I can see, it's good to merge.

I did check to see whether the `&` character in new file names might be a problem for cloning the repo on any OSs - https://en.wikipedia.org/wiki/Filename - And it's fine....
It just says the following, but that's already true for a bunch of files in the hub, that have spaces in their names:

> Note 1: While they are allowed in Unix file and folder names, most Unix shells require specific characters such as spaces, <, >, |, \, and sometimes :, (, ), &, ;, #, as well as wildcards such as ? and *, to be quoted or escaped:

After it's merged, we might want to update the tree-view of the directory structure, for the new directory... (/cc @argenos )

Approved! :-)

**Comment by SlRvb** [comment]
Oh I hadn't realized that ampersand might be an issue 👀. Just to stay on the safe side, since it's just the 1 file, I changed the name and added an alias for the ampersand version for search at least.

**Comment by claremacrae** [comment]
> Oh I hadn't realized that ampersand might be an issue 👀. Just to stay on the safe side, since it's just the 1 file, I changed the name and added an alias for the ampersand version for search at least.

I do still think it's fine - and thanks for renaming the DnD one... but also just for completion (sorry) to note that there is an & in "Button Action & Trait Templates.md"...

**Comment by claremacrae** [comment]
I should have checked - sorry - there are already files and folders with & in the name:

```
./03 - Showcases & Templates
./03 - Showcases & Templates/🗂️ 03 - Showcases & Templates.md
./04 - Guides, Workflows, & Courses
./04 - Guides, Workflows, & Courses/🗂️ 04 - Guides, Workflows, & Courses.md
./01 - Community/Obsidian Roundup/2021-10-02  Premade Concept Hierarchies & a Virtual Community Meeting Space.md
./01 - Community/Obsidian Roundup/2021-10-15  More WYSIWYG Functionality & Some Really Nice Documentation.md
./01 - Community/Obsidian Roundup/2021-10-23  New Calendar & Code Renders in Edit Mode.md
./01 - Community/Obsidian Roundup/2021-10-09  Style Guide Enforcement & Sitemap-style view.md
```

So it really is fine :-)

**Review by argenos — APPROVED** [review]

**Pull request merged**
